name = "forward-widget-hub"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "forward-widget-hub-db"
database_id = "0d1f8abf-8c6a-4fc5-aa77-2b618cf662ec"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "forward-widget-hub-storage"

[vars]
BACKEND = "cloudflare"
ACCESS_PASSWORD = "8888"
ADMIN_PASSWORD = "962464"
